# -----------------------------
# FONT
# -----------------------------
font_family      JetBrains Mono
bold_font        auto
italic_font      auto
bold_italic_font auto
font_size        11.5

# -----------------------------
# CURSOR
# -----------------------------
cursor_shape beam
cursor_blink_interval 0.5

# -----------------------------
# SCROLLBACK
# -----------------------------
scrollback_lines 5000

# -----------------------------
# WINDOW
# -----------------------------
background_opacity 0.90
confirm_os_window_close 0
enable_audio_bell no

# -----------------------------
# COLORS (Mint dark vibe)
# -----------------------------
foreground #e8e8e8
background #1e1e1e

selection_foreground #000000
selection_background #b8ffc8

color0  #2e3436
color1  #cc0000
color2  #50dc78
color3  #c4a000
color4  #3465a4
color5  #75507b
color6  #66ffaa
color7  #d3d7cf
color8  #555753
color9  #ef2929
color10 #8fffaa
color11 #fce94f
color12 #729fcf
color13 #ad7fa8
color14 #b8ffc8
color15 #eeeeec

# -----------------------------
# TABS & SPLITS
# -----------------------------
tab_bar_style powerline
tab_powerline_style slanted
active_tab_foreground   #ffffff
active_tab_background   #50dc78
inactive_tab_foreground #888888
inactive_tab_background #2a2a2a

