# -----------------------------
# FONT
# -----------------------------
font_family      JetBrains Mono
bold_font        auto
italic_font      auto
bold_italic_font auto
font_size        11.5

# -----------------------------
# CURSOR
# -----------------------------
cursor_shape beam
cursor_blink_interval 0.5

# -----------------------------
# SCROLLBACK
# -----------------------------
scrollback_lines 5000

# -----------------------------
# WINDOW
# -----------------------------
background_opacity 0.90
confirm_os_window_close 0
enable_audio_bell no

# -----------------------------
# COLORS (Mint dark vibe)
# -----------------------------
foreground #e8e8e8
background #1e1e1e

selection_foreground #000000
selection_background #ffb3b3

color0  #2e3436
color1  #ff4646
color2  #4e9a06
color3  #c4a000
color4  #a83232
color5  #75507b
color6  #ff9966
color7  #d3d7cf
color8  #555753
color9  #ff6b6b
color10 #8ae234
color11 #fce94f
color12 #ff8080
color13 #ad7fa8
color14 #ffb3a3
color15 #eeeeec

# -----------------------------
# TABS & SPLITS
# -----------------------------
tab_bar_style powerline
tab_powerline_style slanted
active_tab_foreground   #ffffff
active_tab_background   #ff4646
inactive_tab_foreground #888888
inactive_tab_background #2a2a2a

