preload = /home/mis/.config/hypr/wallpapers/green/1.jpg
preload = /home/mis/.config/hypr/wallpapers/green/5.jpg
preload = /home/mis/.config/hypr/wallpapers/green/9.jpg

wallpaper = HDMI-A-3,/home/mis/.config/hypr/wallpapers/green/1.jpg
wallpaper = HDMI-A-2,/home/mis/.config/hypr/wallpapers/green/5.jpg
wallpaper = HDMI-A-1,/home/mis/.config/hypr/wallpapers/green/9.jpg

splash = false
