preload = /home/streak/.config/hypr/wallpapers/1.jpg

wallpaper {
    monitor = eDP-1
    path = /home/streak/.config/hypr/wallpapers/1.jpg
}

wallpaper {
    monitor = HDMI-A-1
    path = /home/streak/.config/hypr/wallpapers/1.jpg
}

splash = false
