exec-once = waybar -c ~/.config/waybar/config-left.jsonc
exec-once = waybar -c ~/.config/waybar/config-right.jsonc


exec-once = wl-paste --type text --watch cliphist store
exec-once = wl-paste --type image --watch cliphist store
#exec-once = hyprpanel
#exec-once = hyprpaper
exec-once = hyprlock


#exec-once = ~/.config/hypr/workspace-wallpaper.sh

exec-once = swww-daemon
exec-once = sleep 1 && ~/.config/hypr/workspace-wallpaper.sh