exec-once = waybar -c ~/.config/waybar/demeter-cyan/config.jsonc -s ~/.config/waybar/demeter-cyan/style.css &

exec-once = wl-paste --type text --watch cliphist store
exec-once = wl-paste --type image --watch cliphist store
#exec-once = hyprpanel
#exec-once = hyprpaper
#exec-once = hyprlock

exec-once = awww-daemon
exec-once = ~/.config/hypr/workspace-wallpaper.sh

