bind = $mainMod, K, exec, \
hyprctl switchxkblayout all next; \
sleep 0.05; \
LAYOUT=$(hyprctl devices -j | jq -r '.keyboards[] | select(.main == true) | .active_keymap'); \
if echo "$LAYOUT" | grep -qi "intl"; then \
  hyprctl notify 1 2000 "rgb(00ff00)" "Layout: Ñ Ready Mañas ✨"; \
else \
  hyprctl notify 1 2000 "rgb(ffffff)" "Layout: US Standard ⏳"; \
fi
